-- 코드를 입력하세요
SELECT PRODUCT_CODE, (sum(SALES_AMOUNT)*p.PRICE) as SALES
FROM PRODUCT as p JOIN OFFLINE_SALE as o ON p.PRODUCT_ID = o.PRODUCT_ID
GROUP BY p.PRODUCT_ID
ORDER BY SALES DESC, PRODUCT_CODE ASC;